### ISSUE TITLE
Trigger on Change Events

### ISSUE THREAD

**Issue by fl43** [appero-com/MyTriggers#4]
I think it is time to support Change Events as well. Would that be an addition we can count on in the near future?

Thanks a lot in advance.

Cheers
Falk

**Comment by Szandor72** [comment]
Hello Falk,

can you please elaborate? 

I am confused since technically, Change Data Capture on Apex side is handled via a normal Trigger, e.g. 

`trigger MyAccountChangeTrigger on AccountChangeEvent (after insert) { //... }`

Since `AccountChangeEvent` is an sObject, myTriggers should be able to handle it.

`List<AccountChangeEvent> changedAccountEvents = (List<AccountChangeEvent>)records;`

I imagine, you might not be able to select the CDC Event in the Trigger settings yet. If this it the case, please have a look on the suggested workaround for [setup objects](https://github.com/appero-com/MyTriggers/issues/2)

Sz

**Comment by fl43** [comment]
Hello Szandor
I want to use the framework for the Opportunity Contact Role Change Event (as a workaround for missing triggers on the Opportunity Contact Role itself). 
Sadly I cannot select this change event as it is not appearing in the dropdown list. And even the AccountChangeEvent cannot be selected in the configuration.

And yes, I could implement this myself, but it would be much nicer if it would be supported out of the box.

Cheers
Falk
